# Generated by Django 5.2.9 on 2026-04-27 00:00

from decimal import Decimal

from django.db import migrations, models


def populate_total_amount(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")
    for order in Order.objects.all():
        total = Decimal("0")
        for item in OrderItem.objects.filter(order=order):
            total += item.price * item.quantity
        order.total_amount = total
        if order.status == "cancelled":
            order.payment_status = "cancelled"
            order.is_paid = False
        elif order.is_paid or order.status in {"paid", "delivered", "shipped"}:
            order.status = "paid"
            order.payment_status = "paid"
            order.is_paid = True
        else:
            order.status = "pending"
            order.payment_status = "pending"
            order.is_paid = False
        order.save(update_fields=["total_amount", "status", "payment_status", "is_paid"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=120, verbose_name="Payment ID"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("paid", "Pagado"),
                    ("cancelled", "Cancelado"),
                    ("failed", "Fallido"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Estado de pago",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("paid", "Pagado"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(populate_total_amount, migrations.RunPython.noop),
    ]
