# Generated by Django 5.2.9 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_payment_fields_order_total_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_token",
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name="Payment Token"),
        ),
    ]
