# Generated by Django 5.2.9 on 2026-06-13 04:47

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def populate_order_tax_fields(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.all().only("id", "total_amount"):
        gross = Decimal(order.total_amount or 0).quantize(Decimal("1"), rounding=ROUND_HALF_UP)
        net = (gross / Decimal("1.19")).quantize(Decimal("1"), rounding=ROUND_HALF_UP) if gross > 0 else Decimal("0")
        tax = gross - net
        Order.objects.filter(pk=order.pk).update(
            net_amount=net,
            tax_amount=tax,
            tax_rate=Decimal("19"),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_discount_amount_order_promo_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='Tasa IVA'),
        ),
        migrations.RunPython(populate_order_tax_fields, migrations.RunPython.noop),
    ]
