# Generated by Django 5.2.9 on 2026-06-21 22:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_net_amount_order_tax_amount_order_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transportista'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de despacho'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('not_started', 'Aún no preparado'), ('preparing', 'Preparando pedido'), ('packed', 'Pedido empaquetado'), ('ready_to_ship', 'Listo para despacho'), ('shipped', 'Despachado'), ('in_transit', 'En tránsito'), ('out_for_delivery', 'En reparto'), ('delivered', 'Entregado'), ('delayed', 'Con demora'), ('failed_delivery', 'Entrega fallida'), ('returned', 'Devuelto'), ('cancelled', 'Envío cancelado')], default='not_started', max_length=20, verbose_name='Estado de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de seguimiento'),
        ),
        migrations.CreateModel(
            name='OrderShippingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Aún no preparado'), ('preparing', 'Preparando pedido'), ('packed', 'Pedido empaquetado'), ('ready_to_ship', 'Listo para despacho'), ('shipped', 'Despachado'), ('in_transit', 'En tránsito'), ('out_for_delivery', 'En reparto'), ('delivered', 'Entregado'), ('delayed', 'Con demora'), ('failed_delivery', 'Entrega fallida'), ('returned', 'Devuelto'), ('cancelled', 'Envío cancelado')], max_length=20, verbose_name='Estado de envío')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='Mensaje para cliente')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_events', to='orders.order')),
            ],
            options={
                'verbose_name': 'Evento de envío',
                'verbose_name_plural': 'Eventos de envío',
                'ordering': ('occurred_at', 'id'),
            },
        ),
    ]
