# Generated by Django 5.2.9 on 2026-06-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('discount_type', models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Codigo promocional',
                'verbose_name_plural': 'Codigos promocionales',
                'ordering': ['code'],
            },
        ),
    ]
