# Generated by Django 5.2.9 on 2026-06-13 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_seed_xclusiv15'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
