# Generated by Django 5.2.9 on 2026-06-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('discount_code', models.CharField(default='XCLUSIV15', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suscriptor newsletter',
                'verbose_name_plural': 'Suscriptores newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
