# Generated by Django 5.2.9 on 2026-04-27 00:00

from django.db import migrations, models


def migrate_product_images_to_urls(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    ProductImage = apps.get_model("catalog", "ProductImage")

    for product_image in ProductImage.objects.all():
        image_field = getattr(product_image, "image", None)
        if image_field and getattr(image_field, "name", ""):
            try:
                product_image.image_url = image_field.url
            except Exception:
                product_image.image_url = image_field.name
            product_image.save(update_fields=["image_url"])

    for product in Product.objects.all():
        main_image = (
            ProductImage.objects.filter(product=product, is_main=True).order_by("ordering", "id").first()
            or ProductImage.objects.filter(product=product).order_by("ordering", "id").first()
        )
        if main_image and main_image.image_url:
            product.image_url = main_image.image_url
            product.save(update_fields=["image_url"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_discount_price_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="Imagen principal"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(blank=True, default="", verbose_name="URL de imagen"),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_product_images_to_urls, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="productimage",
            name="image",
        ),
    ]
