# Generated by Django 5.2.9 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_image_url_and_cloudinary_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(verbose_name="URL de imagen"),
        ),
    ]
