# Generated by Django 5.2.9 on 2026-06-18 17:56

from django.db import migrations, models


def seed_size_options(apps, schema_editor):
    SizeOption = apps.get_model("catalog", "SizeOption")
    Category = apps.get_model("catalog", "Category")

    size_rows = [
        ("XS", "XS", "clothing", 10),
        ("S", "S", "clothing", 20),
        ("M", "M", "clothing", 30),
        ("L", "L", "clothing", 40),
        ("XL", "XL", "clothing", 50),
        ("XXL", "XXL", "clothing", 60),
        ("36", "36", "shoes", 10),
        ("37", "37", "shoes", 20),
        ("38", "38", "shoes", 30),
        ("39", "39", "shoes", 40),
        ("40", "40", "shoes", 50),
        ("41", "41", "shoes", 60),
        ("42", "42", "shoes", 70),
        ("43", "43", "shoes", 80),
        ("44", "44", "shoes", 90),
        ("45", "45", "shoes", 100),
        ("46", "46", "shoes", 110),
        ("ONE_SIZE", "One Size", "accessory", 10),
        ("UNICA", "Única", "accessory", 20),
        ("AJUSTABLE", "Ajustable", "accessory", 30),
    ]

    for code, name, size_type, ordering in size_rows:
        SizeOption.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "size_type": size_type,
                "ordering": ordering,
                "is_active": True,
            },
        )

    codes_by_type = {
        "clothing": ["XS", "S", "M", "L", "XL", "XXL"],
        "shoes": ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46"],
        "accessory": ["ONE_SIZE", "UNICA", "AJUSTABLE"],
    }
    options_by_code = {option.code: option for option in SizeOption.objects.filter(code__in=sum(codes_by_type.values(), []))}

    category_size_types = {
        "accesories-xclusiv": "accessory",
        "bags-001xclusiv": "accessory",
        "clothing-001xclusiv": "clothing",
        "hoodies--001xclusiv": "clothing",
        "jackets-001xclusiv": "clothing",
        "outerwear-001xclusiv": "clothing",
        "pants-001xclusiv": "clothing",
        "sneakers-xclusiv": "shoes",
        "t-shirts-001xclusiv": "clothing",
    }

    for slug, size_type in category_size_types.items():
        category = Category.objects.filter(slug=slug).first()
        if not category:
            continue
        size_options = [options_by_code[code] for code in codes_by_type[size_type] if code in options_by_code]
        category.size_options.add(*size_options)

    category_visuals = {
        "accesories-xclusiv": ("home/airmutblackhome.jpg", "Detalles xclusiv"),
        "bags-001xclusiv": ("home/20251204_072107000_iOS.jpg", "Carry pieces"),
        "clothing-001xclusiv": ("home/ropa.jpg", "Clothing edit"),
        "hoodies--001xclusiv": ("home/hombreCate.jpg", "Hoodies"),
        "jackets-001xclusiv": ("home/retro4bcathome.jpg", "Outer layers"),
        "outerwear-001xclusiv": ("home/airforcehome.jpg", "Outerwear"),
        "pants-001xclusiv": ("home/mujerCate.jpg", "Pants"),
        "sneakers-xclusiv": ("home/airmutblackhome2.png", "Sneakers"),
        "t-shirts-001xclusiv": ("home/airforcelv8black.jpg", "T-Shirts"),
    }

    for slug, (image_path, eyebrow) in category_visuals.items():
        Category.objects.filter(slug=slug).update(
            image_path=image_path,
            visual_eyebrow=eyebrow,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_new_arrivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, verbose_name='Nombre visible')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('size_type', models.CharField(choices=[('clothing', 'Ropa'), ('shoes', 'Calzado'), ('accessory', 'Accesorio'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'ordering': ['size_type', 'ordering', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=160, verbose_name='Texto alternativo'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.CharField(blank=True, help_text='Ruta dentro de static, por ejemplo home/ropa.jpg.', max_length=255, verbose_name='Imagen categoria static'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Imagen categoria URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='visual_eyebrow',
            field=models.CharField(blank=True, max_length=80, verbose_name='Etiqueta visual'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(max_length=20, verbose_name='Talla'),
        ),
        migrations.AddField(
            model_name='category',
            name='size_options',
            field=models.ManyToManyField(blank=True, related_name='categories', to='catalog.sizeoption', verbose_name='Tallas disponibles'),
        ),
        migrations.RunPython(seed_size_options, migrations.RunPython.noop),
    ]
